### Return 200: OK response from GET request at root
GET http://127.0.0.1:5000/chatbot HTTP/1.1

### GET chatbot prediction message from POST request
POST http://127.0.0.1:5000/chatbot/predict HTTP/1.1
content-type: application/json

{
  "message": "How are you doing today, Algee?"
}

### GET chatbot prediction message from POST request
POST http://127.0.0.1:5000/chatbot/predict HTTP/1.1
content-type: application/json

{
  "message": "joke"
}

### GET guidance to use the system from POST request
POST http://127.0.0.1:5000/chatbot/predict HTTP/1.1
content-type: application/json

{
  "message": "I don't know how to use this system. Can you help me?"
}

### GET "the weather" from POST request
POST http://127.0.0.1:5000/chatbot/predict HTTP/1.1
content-type: application/json

{
  "message": "What's the weather like here?"
}

### GET life questions answered ambigiously from POST request
POST http://127.0.0.1:5000/chatbot/predict HTTP/1.1
content-type: application/json

{
  "message": "How do I live life to the fullest?"
}

### GET 422: Unprocessable Entity response from POST request
POST http://127.0.0.1:5000/chatbot/predict HTTP/1.1
content-type: application/json

{
  "request": "I don't know how to use this system. Can you help me?"
}

### GET 404: Not Found response from POST request
GET http://127.0.0.1:5000/chatbot/ask HTTP/1.1
content-type: application/json

{
  "request": "I don't know how to use this system. Can you help me?"
}

### Return 405: Method Not Allowed from a DELETE request
DELETE http://127.0.0.1:5000/chatbot/ HTTP/1.1

### GET response from POST request
POST http://127.0.0.1:5000/chatbot/predict HTTP/1.1
content-type: application/json

{
  "message": "I don't know how to use this system. Can you help me?"
}

#################### ON RENDER URL ####################

### Return 200: OK response from GET request at root
GET https://ai-flask-m190.onrender.com/chatbot HTTP/1.1

### GET chatbot prediction message from POST request
POST https://ai-flask-m190.onrender.com/chatbot/predict HTTP/1.1
content-type: application/json

{
  "message": "How are you doing today, Algee?"
}

### GET chatbot prediction message from POST request
POST https://ai-flask-m190.onrender.com/chatbot/predict HTTP/1.1
content-type: application/json

{
  "message": "joke"
}

### GET guidance to use the system from POST request
POST https://ai-flask-m190.onrender.com/chatbot/predict HTTP/1.1
content-type: application/json

{
  "message": "I don't know how to use this system. Can you help me?"
}

### GET "the weather" from POST request
POST https://ai-flask-m190.onrender.com/chatbot/predict HTTP/1.1
content-type: application/json

{
  "message": "What's the weather like here?"
}

### GET life questions answered ambigiously from POST request
POST https://ai-flask-m190.onrender.com/chatbot/predict HTTP/1.1
content-type: application/json

{
  "message": "How do I live life to the fullest?"
}

### GET 422: Unprocessable Entity response from POST request
POST https://ai-flask-m190.onrender.com/chatbot/predict HTTP/1.1
content-type: application/json

{
  "request": "I don't know how to use this system. Can you help me?"
}

### GET 404: Not Found response from POST request
GET https://ai-flask-m190.onrender.com/chatbot/ask HTTP/1.1
content-type: application/json

{
  "request": "I don't know how to use this system. Can you help me?"
}

### Return 405: Method Not Allowed from a DELETE request
DELETE https://ai-flask-m190.onrender.com/chatbot/ HTTP/1.1

### Render URL ###

### GET response from POST request
POST https://ai-flask-m190.onrender.com/chatbot/predict HTTP/1.1
content-type: application/json

{
  "message": "I don't know how to use this system. Can you help me?"
}
